#!/usr/bin/env python3
"""Builds Sources/VoidMac/ChampionCombatData.swift: melee or ranged, basic-attack missile speed, class and ARAM damage dealt per champion from the wiki's ChampionData module."""
import json, pathlib, re, sys, urllib.request

URL = "https://wiki.leagueoflegends.com/en-us/Module:ChampionData/data?action=raw"
OUT = pathlib.Path(__file__).resolve().parent.parent / "Sources/VoidMac/ChampionCombatData.swift"


class Lua:
    """Just enough of a Lua table-constructor reader for the module: strings, numbers, booleans, nil and nested tables."""

    def __init__(self, text):
        self.text, self.i = text, 0

    def skip(self):
        while self.i < len(self.text):
            if self.text.startswith("--", self.i):
                end = self.text.find("\n", self.i)
                self.i = len(self.text) if end < 0 else end + 1
            elif self.text[self.i] in " \t\r\n":
                self.i += 1
            else:
                return

    def value(self):
        self.skip()
        ch = self.text[self.i]
        if ch == "{":
            return self.table()
        if ch in "\"'":
            end = self.text.index(ch, self.i + 1)
            while self.text[end - 1] == "\\":
                end = self.text.index(ch, end + 1)
            out = self.text[self.i + 1:end]
            self.i = end + 1
            return out
        match = re.compile(r"true|false|nil|[-+*/.\deE ()]+").match(self.text, self.i)
        if not match:
            raise ValueError(f"unexpected {self.text[self.i:self.i + 30]!r}")
        self.i = match.end()
        word = match.group(0).strip()
        if word in ("true", "false", "nil"):
            return {"true": True, "false": False, "nil": None}[word]
        return float(eval(word, {"__builtins__": {}}))

    def table(self):
        self.i += 1
        keyed, listed = {}, []
        while True:
            self.skip()
            if self.text[self.i] == "}":
                self.i += 1
                return keyed if keyed else listed
            if self.text[self.i] == "[":
                self.i += 1
                key = self.value()
                self.skip()
                self.i += 1
                self.skip()
                self.i += 1
                keyed[key] = self.value()
            else:
                name = re.compile(r"[A-Za-z_]\w*\s*=").match(self.text, self.i)
                if name:
                    self.i = name.end()
                    keyed[name.group(0)[:-1].strip()] = self.value()
                else:
                    listed.append(self.value())
            self.skip()
            if self.text[self.i] in ",;":
                self.i += 1


def normalize(name):
    return "".join(ch for ch in name.lower() if ch.isalpha())


text = urllib.request.urlopen(urllib.request.Request(URL, headers={"User-Agent": "VoidMac combat data generator"}), timeout=120).read().decode()
data = Lua(text[text.index("return") + len("return"):]).value()
rows = []
for name, champion in sorted(data.items()):
    if not isinstance(champion, dict) or "apiname" not in champion:
        continue
    stats = champion.get("stats") or {}
    row = {"k": normalize(champion["apiname"]), "r": 1 if champion.get("rangetype") == "Ranged" else 0, "t": champion.get("herotype") or ""}
    speed = stats.get("missile_speed")
    if isinstance(speed, float) and speed > 0:
        row["m"] = int(speed)
    dealt = (stats.get("aram") or {}).get("dmg_dealt")
    if isinstance(dealt, float) and dealt != 1:
        row["a"] = dealt
    rows.append(row)
payload = json.dumps(rows, separators=(",", ":"), ensure_ascii=True)
assert '"""' not in payload and "\\" not in payload
OUT.write_text(f'''import Foundation

/** Per champion, generated by Tools/generate_combat.py from the League of Legends Wiki ChampionData module: ranged (1) or melee, basic-attack missile speed, class, ARAM damage dealt. */
enum ChampionCombatData {{
    static let json = """
{payload}
"""
}}
''')
print(f"wrote {OUT}: {len(rows)} champions, {sum(1 for r in rows if 'm' in r)} with a missile speed, {sum(1 for r in rows if r['r'])} ranged", file=sys.stderr)
