#!/usr/bin/env python3
"""Builds Sources/VoidMac/ChampionModelData.swift: per-unit mesh height, health bar height and selection sizes from CommunityDragon bins and meshes."""
import json, struct, sys, urllib.request, concurrent.futures, pathlib, re

UA = {"User-Agent": "VoidMac champion model generator"}
DD = "https://ddragon.leagueoflegends.com"
CD = "https://raw.communitydragon.org/latest/game/"
OUT = pathlib.Path(__file__).resolve().parent.parent / "Sources/VoidMac/ChampionModelData.swift"
EXTRA_UNITS = [("practicetool_targetdummy", "Target Dummy")]

def get(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read()

def normalize(name):
    return "".join(ch for ch in name.lower() if ch.isalpha())

def mesh_top(data):
    """Highest vertex of the bind pose (model units, y up) from a .skn file."""
    magic, major, minor = struct.unpack_from("<IHH", data, 0)
    if magic != 0x00112233:
        raise ValueError("not a skn")
    off = 8
    if major >= 2:
        count = struct.unpack_from("<I", data, off)[0]
        off += 4 + count * 80
    if major == 4:
        off += 4
    index_count, vertex_count = struct.unpack_from("<II", data, off)
    off += 8
    size = 52
    if major == 4:
        size, vertex_type = struct.unpack_from("<II", data, off)
        off += 8
        box = struct.unpack_from("<6f", data, off)
        return box[4]
    off += index_count * 2
    top = -1e9
    for i in range(vertex_count):
        top = max(top, struct.unpack_from("<f", data, off + i * size + 4)[0])
    return top

def unit(cid, name):
    key = cid.lower()
    out = {"k": normalize(cid), "n": name}
    try:
        record = json.loads(get(f"{CD}data/characters/{key}/{key}.bin.json"))
        root = next((v for k, v in record.items() if isinstance(v, dict) and v.get("__type") == "CharacterRecord"), {})
    except Exception as e:
        print(f"  {cid}: no record ({e})", file=sys.stderr)
        root = {}
    if root.get("healthBarHeight") is not None:
        out["b"] = round(float(root["healthBarHeight"]), 1)
    out["sh"] = round(float(root.get("selectionHeight") or 0), 1)
    out["sr"] = round(float(root.get("selectionRadius") or 100), 1)
    out["g"] = round(float(root.get("overrideGameplayCollisionRadius") or 65), 1)
    scale = 1.0
    top = None
    try:
        skin = json.loads(get(f"{CD}data/characters/{key}/skins/skin0.bin.json"))
        props = next((v for k, v in skin.items() if isinstance(v, dict) and v.get("__type") == "SkinCharacterDataProperties"), {})
        mesh = props.get("skinMeshProperties") or {}
        scale = float(mesh.get("skinScale") or 1.0)
        path = mesh.get("simpleSkin")
        if path:
            top = mesh_top(get(CD + path.lower()))
        if top is None and mesh.get("overrideBoundingBox"):
            top = float(mesh["overrideBoundingBox"][1])
    except Exception as e:
        print(f"  {cid}: no mesh ({e})", file=sys.stderr)
    if top is None:
        top = float(root.get("selectionHeight") or 200)
        print(f"  {cid}: mesh height from selectionHeight {top}", file=sys.stderr)
    out["h"] = round(top * scale)
    return out

VERSION = json.loads(get(f"{DD}/api/versions.json"))[0]
champions = list(json.loads(get(f"{DD}/cdn/{VERSION}/data/en_US/champion.json"))["data"].values())
print(f"Data Dragon {VERSION}, {len(champions)} champions", file=sys.stderr)
jobs = [(c["id"], c["name"]) for c in champions] + EXTRA_UNITS
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
    table = list(pool.map(lambda j: unit(*j), jobs))
table.sort(key=lambda u: u["k"])
payload = json.dumps(table, separators=(",", ":"), ensure_ascii=True)
assert '"""' not in payload and "\\" not in payload
swift = f'''import Foundation

/** Unit sizes for every champion and the practice dummy, generated by Tools/generate_champions.py from Data Dragon {VERSION} and CommunityDragon. */
enum ChampionModelData {{
    static let version = "{VERSION}"
    static let json = """
{payload}
"""
}}
'''
OUT.write_text(swift)
missing = sum(1 for u in table if "b" not in u)
print(f"wrote {OUT} ({len(table)} units, {missing} without healthBarHeight)", file=sys.stderr)
